### ISSUE TITLE
What's the zookeeper config?

### ISSUE THREAD

**Issue by zhanglistar** [azat/keeper-zookeeper#4]
@azat Could you please post the config of zookeeper?
In the config of clickhouse-keeper, force_sync is true by default and I see that you commented out, that is, forece_sync is open.
That will affect the result a lot.
So, what's the zookeeper's config?
Thanks a lot.
Hope you replay.

**Comment by azat** [comment]
>In the config of clickhouse-keeper, force_sync is true by default and I see that you commented out, that is, forece_sync is open.
>That will affect the result a lot.

Of course, but running coordinator without fsync is useless, there is no guarantee that the data will not be corrupted

ZooKeeper has fsync by default and AFAIR it cannot be turned OFF

>So, what's the zookeeper's config?

The config is default, I don't tune anything.

And I don't think that on such a load it will make any difference, because this test does not creates tons of znodes, so no need to tune memory.
